name: Trigger auto deployment for container-app-wjf2ecfznlvyc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/container-app-wjf2ecfznlvyc-AutoDeployTrigger-0bb4ef26-5688-4c08-97f6-4bf89f38c223.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPWJF2ECFZNLVYC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPWJF2ECFZNLVYC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPWJF2ECFZNLVYC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistrywjf2ecfznlvyc.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPWJF2ECFZNLVYC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPWJF2ECFZNLVYC_REGISTRY_PASSWORD }}
          containerAppName: container-app-wjf2ecfznlvyc
          resourceGroup: simplewhaledemo98b7
          imageToBuild: containerregistrywjf2ecfznlvyc.azurecr.io/container-app-wjf2ecfznlvyc:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


